services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql_server_db
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 20s
      retries: 25
      start_period: 300s

  api:
    build:
      context: ./APIContainer
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "5000:8080"
      - "5001:7128"
    environment:
      - ASPNETCORE_URLS=http://+:7128
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      db:
        condition: service_healthy